### ISSUE TITLE
Syntax Theme Settings Button Misaligned

### ISSUE THREAD

**Issue by grayghostvisuals** [tclem/atom-solarized-dark-ui#12]
Settings button (cog wheel) needs some lovin' under syntax theme. Currently using version 0.28.0

![screenshot 2017-07-07 23 16 15](https://user-images.githubusercontent.com/934322/27982212-7a46a89e-636a-11e7-8ec0-46956f8ac1f3.png)

**Comment by tclem** [comment]
Should be sorted in v0.28.1 which I just published.
