### ISSUE TITLE
Not showing up in the list of installable packages in Atom

### ISSUE THREAD

**Issue by jlevers** [tclem/atom-solarized-dark-ui#3]
Not totally sure if this is where I should be submitting this problem, but when I try to install this program in Atom, it does not show up in the list of installable packages.

**Comment by tclem** [comment]
Whoops! I'd never actually published to apm :blush:. Should be up there now!

https://atom.io/packages/atom-solarized-dark-ui

**Comment by jlevers** [comment]
Awesome, thank you.
