### ISSUE TITLE
more contrast for selected tab

### ISSUE THREAD

**Issue by grayghostvisuals** [tclem/atom-solarized-dark-ui#4]
At times it can be hard to see the selected tab and for low vision users it would be of help to give the tab a bit more contrast.

![screenshot 2016-09-13 12 35 25](https://cloud.githubusercontent.com/assets/934322/18513795/f0ae435e-7a5c-11e6-975f-0a454cc33242.png)

**Comment by tclem** [comment]
👍 Good call. Made an attempt to improve contrast in #5, LMKWYT.

**Comment by grayghostvisuals** [comment]
@tclem Yep that works for me. Thanks 🍻
