### ISSUE TITLE
Progress bar is not animated. 

### ISSUE THREAD

**Issue by jianghaizhu** [tclem/atom-solarized-dark-ui#7]
The progress bar on the bottom appears static. In themes like "Atom Dark" or "One Dark", the bar is animated when something is running. 

<img width="158" alt="screen shot" src="https://cloud.githubusercontent.com/assets/16137435/18721950/cb6286e2-8000-11e6-869e-4498f79d74d7.png">

**Comment by tclem** [comment]
👍  Good idea!

I don't have a lot of time to spend on this project at the moment, but I'm more than happy to review a pull request.
